FROM ubuntu
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:neovim-ppa/stable 
RUN apt-get update
RUN apt-get install neovim -y
RUN apt-get install python-dev python-pip python3-dev python3-pip -y
RUN apt-get install git -y



